default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rootstrap
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: target_dev

test:
  <<: *default
  database: target_test

production:
  <<: *default
  database: target_prod